# Manual mapping of RomM slugs to device folder names and platform icons for es systems
# This is sometimes needed to match custom system folders with defaults, for example ES-DE uses roms/gc and some Batocera forks use roms/gamecube
# https://gitlab.com/es-de/emulationstation-de/-/blob/master/resources/systems/unix/es_systems.xml

SUPPORTED_PLATFORMS_FS_MAP = {
    'amiga': 'AMIGA',
    'amstrad_cpc': 'CPC',
    'arcade': 'ARCADE',
    'arduboy': 'ARDUBOY',
    'atari2600': 'ATARI',
    'atari8bit': 'EIGHTHUNDRED',
    'atari5200': 'FIFTYTWOHUNDRED',
    'atari7800': 'SEVENTYEIGHTHUNDRED',
    'lynx': 'LYNX',
    'sufami': 'SUFAMI',
    'wonderswan': 'WS',
    'wonderswan_color': 'WSC',
    'cps1': 'CPS1',
    'cps2': 'CPS2',
    'cps3': 'CPS3',
    'colecovision': 'COLECO',
    'c64': 'COMMODORE',
    'vic20': 'VIC20',
    'doom': 'DOOM',
    'channel_f': 'FAIRCHILD',
    'fds': 'FDS',
    'media': 'MEDIA',
    'gw': 'GW',
    'vectrex': 'VECTREX',
    'odyssey2': 'ODYSSEY',
    'mame2003plus': 'MAME2003PLUS',
    'intellivision': 'INTELLIVISION',
    'megaduck': 'MEGADUCK',
    'dos': 'DOS',
    'msx': 'MSX',
    'msx2': 'MSX',  # same folder for both MSX and MSX2
    'supergrafx': 'SGFX',
    'pcecd': 'PCECD',
    'tg16': 'PCE',
    'pce': 'PCE',
    'n64': 'N64',
    'nds': 'NDS',
    'nes': 'FC',
    'gba': 'GBA',
    'gbc': 'GBC',
    'gb': 'GB',
    'pokemon_mini': 'POKE',
    'satellaview': 'SATELLAVIEW',
    'sgb': 'SGB',
    'snes': 'SFC',
    'vb': 'VB',
    'openbor': 'OPENBOR',
    'pico8_fake08': 'FAKE08',
    'pico8': 'PICO8',
    'psp': 'PSP',
    'quake': 'QUAKE',
    'ports': 'PORTS',
    'scummvm': 'SCUMMVM',
    'sega32x': 'THIRTYTWOX',
    'segacd': 'SEGACD',
    'dreamcast': 'DC',
    'gamegear': 'GG',
    'msumd': 'MSUMD',
    'genesis': 'MD',
    'megadrive': 'MD',  # alias for Genesis
    'mastersystem': 'MS',
    'sg1000': 'SEGASGONE',
    'x68000': 'X68000',
    'zxspectrum': 'ZXS',
    'msu1': 'MSU1',
    'neogeocd': 'NEOCD',
    'ngp': 'NGP',
    'ngpc': 'NGPC',
    'neogeo': 'NEOGEO',
    'psx': 'PS',
    'tic80': 'TIC',
    'videopac': 'VIDEOPAC',
    'supervision': 'SUPERVISION',
    'wolf3d': 'WOLF',
}


SUPPORTED_PLATFORMS = frozenset(SUPPORTED_PLATFORMS_FS_MAP.keys())
SUPPORTED_PLATFORMS_FS = frozenset(SUPPORTED_PLATFORMS_FS_MAP.values())
