name: Build and Push zip installer

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_ENV
          sed -i "s/<version>/$VERSION/" .romm/__version__.py

      - name: Run build script
        run: |
          chmod +x scripts/build.sh
          ./scripts/build.sh

      - name: Debug artifact path
        run: ls -lah .dist || echo "No files in .dist"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: romm_muOS_install_${{ env.version }}.zip
          path: .dist/romm_muOS_install_${{ env.version }}.zip
